export const projectHistoryData = [
  {
    id: 1,
    sr: 1,
    first_name: "Gazmen",
    last_name: "Emily",
    email: "gazmen.emil@gmail.com",
    download_link: "https://example.com/downloads/project-1.zip",
    project_name: "E-commerce Website",
    completion_date: "2024-01-15",
    status: "Completed",
  },
  {
    id: 2,
    sr: 2,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    download_link: "https://example.com/downloads/project-2.zip",
    project_name: "Mobile App Design",
    completion_date: "2024-01-10",
    status: "Completed",
  },
  {
    id: 3,
    sr: 3,
    first_name: "Mike",
    last_name: "Johnson",
    email: "mike.johnson@example.com",
    download_link: "https://example.com/downloads/project-3.zip",
    project_name: "Brand Identity",
    completion_date: "2024-01-08",
    status: "Completed",
  },
  {
    id: 4,
    sr: 4,
    first_name: "Sarah",
    last_name: "Williams",
    email: "sarah.williams@example.com",
    download_link: "https://example.com/downloads/project-4.zip",
    project_name: "Website Redesign",
    completion_date: "2024-01-05",
    status: "Completed",
  },
  {
    id: 5,
    sr: 5,
    first_name: "David",
    last_name: "Brown",
    email: "david.brown@example.com",
    download_link: "https://example.com/downloads/project-5.zip",
    project_name: "Logo Design",
    completion_date: "2024-01-03",
    status: "Completed",
  },
  {
    id: 6,
    sr: 6,
    first_name: "Emily",
    last_name: "Davis",
    email: "emily.davis@example.com",
    download_link: "https://example.com/downloads/project-6.zip",
    project_name: "Marketing Materials",
    completion_date: "2023-12-28",
    status: "Completed",
  },
  {
    id: 7,
    sr: 7,
    first_name: "Robert",
    last_name: "Miller",
    email: "robert.miller@example.com",
    download_link: "https://example.com/downloads/project-7.zip",
    project_name: "UI/UX Design",
    completion_date: "2023-12-25",
    status: "Completed",
  },
  {
    id: 8,
    sr: 8,
    first_name: "Lisa",
    last_name: "Wilson",
    email: "lisa.wilson@example.com",
    download_link: "https://example.com/downloads/project-8.zip",
    project_name: "Social Media Kit",
    completion_date: "2023-12-20",
    status: "Completed",
  },
  {
    id: 9,
    sr: 9,
    first_name: "James",
    last_name: "Moore",
    email: "james.moore@example.com",
    download_link: "https://example.com/downloads/project-9.zip",
    project_name: "Business Cards",
    completion_date: "2023-12-18",
    status: "Completed",
  },
  {
    id: 10,
    sr: 10,
    first_name: "Anna",
    last_name: "Taylor",
    email: "anna.taylor@example.com",
    download_link: "https://example.com/downloads/project-10.zip",
    project_name: "Website Development",
    completion_date: "2023-12-15",
    status: "Completed",
  },
];
